title: 'CodersCamp Course 2020 (test) - Wprowadzenie '
description: >-
  Czieszymy się, że postanowiłeś do nas dołączyć w kolejnej edycji CodersCamp.
  Skoro otrzymałeś tę listę zadań, to znaczy, że udało Ci się pomyślnie przejść
  pierwszy etap rekrutacji i jesteś już o krok od dostania się na pełną wersję
  kursu.
template:
  repo: coderscamp2020-test-course-1-template
  name: coderscamp2020-test-course-1
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
